### ISSUE TITLE
CiriQuant output as an input to DEBKS

### ISSUE THREAD

**Issue by amarinderthind** [yangence/DEBKS#1]
Hi! 

Nice approach for DE of Circular RNA.  as you mentioned in your paper,  (PBSI, ψ) which is equivalent to ratio calculations in CIRIquant (except for smaller circRNA). Is there a possibility of using this ratio file (obtained from CIRIquant) directly for DEC of DEBKS? or we need to supply all three files, merge_circ.txt,  merge_linear.txt, and anno_len.txt. 

I got the following error while executing DEBKS anno command 

**_" ValueError: could not create iterator for region 'chr14_GL000194v1_random:92153-92447"_**

It seems regions  are not well defined, however, my input file only has three columns as required 
chr     start   end
chr10   1000677 1001013

Trackback points out the following line in your code... 

annoPos=pd.DataFrame(circPos.apply(lambda x: pos2ano(x,gtfFile,faFile),axis=1).tolist(),columns=['type','strand','gene_id','gene_name','subtype','exon_start','exon_end','len'])"

Bests,
Amarinder

**Comment by colinliuzelin** [comment]
Thanks you for your comment!
1) DEBKS need merge_circ.txt, merge_linear.txt file, and anno_len.txt (optional) as input. Ratio file is not supported.
2) We have fixed the anno command, you can download the current version and try to run your command again.

**Comment by amarinderthind** [comment]
Thank you very much for your help.
