### ISSUE TITLE
FDR values lower than p-values, is it normal?

### ISSUE THREAD

**Issue by amarinderthind** [yangence/DEBKS#2]
Hi, DEC results I obtained from DEBKS has FDR values lower than p-values, is it normal?

delta_pbsi | P | FDR
-- | -- | --
-0.2854 | 1.70E-05 | 4.28E-05
0.268629 | 0.00236421 | 0.005956745
-0.38343 | 0.01893992 | 0.047675749
-0.2866	 | 0.09543357	 | 0
-0.38229	 | 0.00891936	 | 0
-0.31618	 | 0.01089185	 | 0
0.17595	 | 0.80893938	 | 0
-0.13908	 | 0.09969168	 | 0
-0.17217	 | 0.19704871	 | 0
-0.0788	 | 0.64874947	 | 0
-0.13745	 | 0.47811821	 | 0

**Comment by colinliuzelin** [comment]
The strange FDR is caused by the NA value of P. We add a function to check Inf value in input count file which cause the NA value of P.
