### ISSUE TITLE
All delta_pbsi values lower than 0, is it normal?

### ISSUE THREAD

**Issue by MarjanGolshani** [yangence/DEBKS#4]
Hi, DEC results I obtained from DEBKS have all delta_pbsi values lower than 0, is it normal?
In biology, these results seem strange.
Regards,
Marjan 
@yangence @colinliuzelin

**Comment by colinliuzelin** [comment]
Sorry for getting back to you so late. It is normal for most of delta_pbsi values lower than 0, which is caused by disturbance of strong regulation factors. However, it is unusual for all of them lower than 0. In order to confirm the problem, could you provide the dec result file?

**Comment by MarjanGolshani** [comment]
[DEBK_ans.pdf](https://github.com/yangence/DEBKS/files/6409347/DEBK_ans.pdf)
Hi there;
thanks for your reply, here is my file for differentially expressed circRNAs. the P-value and FDR it's reliable for differentially expressed circRNAs,  but all delta_pbsi values lower than 0 and in biology, It does not make sense for all the differentially expressed circRNAs to be expressed more in control samples than in test samples.
can you help me with this problem, please?


> Sorry for getting back to you so late. It is normal for most of delta_pbsi values lower than 0, which is caused by disturbance of strong regulation factors. However, it is unusual for all of them lower than 0. In order to confirm the problem, could you provide the dec result file?

**Comment by colinliuzelin** [comment]
Hi,
The DEBKS_ans.pdf file you provided only contains circRNAs with FDR < 0.5. I think this is a normal result for differentially expressed circRNAs with all delta_pbsi values lower than 0, expecifically in the condition of knockdown/knockoff of a strong regulation factor, such as ADAR, DHX9. Besides, cancer samples usually have lower circRNA expression level. If the delta_pbsi of all circRNAs not only DEC lower than 0, I would like the unselected dec result file for further analysis.
