### ISSUE TITLE
Can DEBKS perform covariate adjustment?

### ISSUE THREAD

**Issue by ChengxuanChen10** [yangence/DEBKS#8]
Hi，
I want to conduct a differential expression analysis within a population disease cohort (sample size >100).
I intend to incorporate covariate adjustments for variables such as sex and age. 
Is DEBKS equipped to facilitate such analysis?

**Comment by colinliuzelin** [comment]
Hi,
No. DEBKS can not perform covariates adjustments. If you find any significant differentially expressed circRNA by DEBKS, I suggest you can check their correlations with covariates to filter out the effects.
Best

**Comment by ChengxuanChen10** [comment]
Thank you~!
